# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: Ships
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Who i am
      run: ls
    # - name: Change solution directory
    #   run: cd ShipsApi && ls
    - name: Restore dependencies
      run: pwd && ls && dotnet restore ShipsApi.sln
    - name: Build
      run: dotnet build ShipsApi.sln --no-restore
    - name: Test
      run: dotnet test ShipsApi.sln --no-build --verbosity normal
